### ISSUE TITLE
ClassCastException invoking DB.getCollections

### ISSUE THREAD

**Issue by ajermakovics** [jankotek/JDBM3#15] opened 2012-02-25 11:35 UTC
Using Alpha2

```
DB db = new DBMaker("db").build();
db.createTreeMap("treemap");
db.getCollections();
```

**Comment by jankotek** [comment] 2012-02-25 14:31
Fixed in git

**Closed as completed by jankotek** 2012-02-25 14:31 UTC

**Comment by jkauzlar** [comment] 2012-03-08 20:35
I'm still getting the same issue with DB#deleteCollection:

Caused by: java.lang.ClassCastException: net.kotek.jdbm.HTree cannot be cast to java.util.Collection
 at net.kotek.jdbm.DBStore.deleteCollection (DBStore.java:401)
    net.kotek.jdbm.DBCache.deleteCollection (DBCache.java:726)

This is from the repo source I downloaded & built about 10 minutes ago.

**Comment by jankotek** [comment] 2012-03-08 23:53
Fixed, thanks

**Comment by jkauzlar** [comment] 2012-03-27 22:09
Hi, this has crept back into head again with getCollections. I haven't retested deleteCollection yet.. thanks
